# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            marktufano
tagline:          
url:			  http://www.marktufano.com

author:
  name:           Mark Tufano
  url:            https://twitter.com/marktufano

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/marktufano/marktufano.github.io

  gems:
  - jekyll-redirect-from
